services:

  cocktail_bdd:
    container_name: ctn_cesi_bdd
    image: mariadb:latest
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: TOOR
      MARIADB_DATABASE: cesi
      MARIADB_USER: roger
      MARIADB_PASSWORD: regor
    profiles: [local, dev, prod]

  cocktail_api:
    container_name: ctn_cocktail_api
    image: alievna/cocktail:main
    restart: always
    depends_on:
      - cocktail_bdd
    environment:
      BDD_HOST: cocktail_bdd
    ports:
      - 23000:15000
    profiles: [dev, prod]
  
  adminer:
    container_name: ctn_cocktail_adminer
    image: adminer
    ports:
        - 3307:8080
    profiles: [dev]
