services:

  cocktail_bdd:
    container_name: ctn_cocktail_bdd
    image: mariadb:latest
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: TOOR
      MARIADB_DATABASE: cocktail
      MARIADB_USER: roger
      MARIADB_PASSWORD: regor
    profiles: [local, dev, prod]
  
  adminer:
    container_name: ctn_cocktail_adminer
    image: adminer
    ports:
        - 3307:8080
    profiles: [dev]
